import type { SeedProduct } from "@/types";

export const SEED_CATEGORIES = [
  { id: "cat-1", name: "SaaS & Technology", slug: "saas-technology" },
  { id: "cat-2", name: "Ecommerce & Retail", slug: "ecommerce-retail" },
  { id: "cat-3", name: "Creative & Agency", slug: "creative-agency" },
  { id: "cat-4", name: "Finance & Fintech", slug: "finance-fintech" },
  { id: "cat-5", name: "Architecture & Real Estate", slug: "architecture-real-estate" },
  { id: "cat-6", name: "Food & Hospitality", slug: "food-hospitality" },
];

export const SEED_PRODUCTS: SeedProduct[] = [
  {
    id: "seed-1",
    name: "Arcadia",
    slug: "arcadia-architecture",
    category: "Architecture & Real Estate",
    product_type: "website",
    price: 145000,
    currency: "NGN",
    overview: "A cinematic architecture studio website with full-screen imagery, project galleries, and award-winning design aesthetics.",
    description: "Arcadia is a premium architecture studio website template built for leading firms that want to make a powerful first impression. Featuring full-screen project photography, smooth parallax scrolling, a sophisticated team section, and an integrated contact system, this template communicates excellence without compromise.\n\nBuilt with performance in mind, Arcadia loads in under two seconds and scores 98+ on Google Lighthouse. The responsive grid adapts beautifully to every screen size, from mobile to ultra-wide displays.",
    demo_url: "https://arcadia-demo.nuvia.store",
    is_featured: true,
    is_published: true,
    primary_image_url: "https://images.unsplash.com/photo-1486325212027-8081e485255e?w=1200&h=900&fit=crop",
    images: [
      "https://images.unsplash.com/photo-1486325212027-8081e485255e?w=1200&h=900&fit=crop",
      "https://images.unsplash.com/photo-1545324418-cc1a3fa10c00?w=1200&h=900&fit=crop",
      "https://images.unsplash.com/photo-1497366216548-37526070297c?w=1200&h=900&fit=crop",
    ],
    features: [
      "Full-screen project gallery with smooth transitions",
      "Parallax scrolling hero section",
      "Award showcase section",
      "Integrated contact and inquiry form",
      "Team profiles with hover effects",
      "Google Maps integration",
      "Mobile-first responsive layout",
      "SEO optimised structure",
    ],
    average_rating: 4.9,
    review_count: 24,
  },
  {
    id: "seed-2",
    name: "Velocity",
    slug: "velocity-saas",
    category: "SaaS & Technology",
    product_type: "website",
    price: 95000,
    currency: "NGN",
    overview: "A modern SaaS marketing website with conversion-focused design, animated feature showcases, and pricing tables.",
    description: "Velocity is a high-converting SaaS landing page template designed for software products that need to communicate value quickly and clearly. Built around conversion psychology, every section guides visitors through an intentional journey from awareness to sign-up.\n\nThe template includes animated feature demonstrations, comparison tables, social proof sections, and a beautifully designed pricing calculator. It integrates with major analytics platforms out of the box.",
    demo_url: "https://velocity-demo.nuvia.store",
    is_featured: true,
    is_published: true,
    primary_image_url: "https://images.unsplash.com/photo-1460925895917-afdab827c52f?w=1200&h=900&fit=crop",
    images: [
      "https://images.unsplash.com/photo-1460925895917-afdab827c52f?w=1200&h=900&fit=crop",
      "https://images.unsplash.com/photo-1551288049-bebda4e38f71?w=1200&h=900&fit=crop",
    ],
    features: [
      "Animated hero with product screenshots",
      "Feature showcase with micro-animations",
      "Pricing tables with toggle (monthly/annual)",
      "Testimonials and social proof sections",
      "Comparison table",
      "Integration logos section",
      "Newsletter signup with email capture",
      "Dark mode support",
    ],
    average_rating: 4.7,
    review_count: 38,
  },
  {
    id: "seed-3",
    name: "Élite",
    slug: "elite-fashion",
    category: "Ecommerce & Retail",
    product_type: "website",
    price: 185000,
    currency: "NGN",
    overview: "A luxury fashion ecommerce platform with editorial editorial layouts, product collections, and seamless checkout experience.",
    description: "Élite is a full-featured fashion ecommerce website built for luxury and premium retail brands. The editorial design language communicates exclusivity through generous white space, sophisticated typography, and cinematic product photography layouts.\n\nThe platform includes a full shopping cart, wishlist, product filtering, collection management, and a streamlined multi-step checkout. Built with performance and mobile-first in mind.",
    demo_url: "https://elite-demo.nuvia.store",
    is_featured: true,
    is_published: true,
    primary_image_url: "https://images.unsplash.com/photo-1445205170230-053b83016050?w=1200&h=900&fit=crop",
    images: [
      "https://images.unsplash.com/photo-1445205170230-053b83016050?w=1200&h=900&fit=crop",
      "https://images.unsplash.com/photo-1558655146-364adaf1fcc9?w=1200&h=900&fit=crop",
    ],
    features: [
      "Editorial product grid layouts",
      "Full shopping cart and wishlist",
      "Advanced product filtering",
      "Multi-step checkout flow",
      "Collection and lookbook pages",
      "Product zoom and gallery",
      "Size guide integration",
      "Order tracking system",
    ],
    average_rating: 4.8,
    review_count: 19,
  },
  {
    id: "seed-4",
    name: "Muse",
    slug: "muse-creative-agency",
    category: "Creative & Agency",
    product_type: "website",
    price: 125000,
    currency: "NGN",
    overview: "A bold creative agency website with asymmetric layouts, dynamic case study presentation, and compelling award-winning aesthetics.",
    description: "Muse is designed for creative studios and agencies that need to showcase their work with the same level of craft they apply to client projects. The asymmetric grid system creates visual dynamism while maintaining an underlying sense of order and intention.\n\nCase studies are presented with full-bleed imagery, strategic typography, and rich narrative sections. The services section uses an elegant expandable layout that communicates expertise without overwhelming.",
    demo_url: "https://muse-demo.nuvia.store",
    is_featured: false,
    is_published: true,
    primary_image_url: "https://images.unsplash.com/photo-1558655146-364adaf1fcc9?w=1200&h=900&fit=crop",
    images: [
      "https://images.unsplash.com/photo-1558655146-364adaf1fcc9?w=1200&h=900&fit=crop",
      "https://images.unsplash.com/photo-1507238691740-187a5b1d37b8?w=1200&h=900&fit=crop",
    ],
    features: [
      "Asymmetric project grid with hover effects",
      "Full-screen case study pages",
      "Services with expandable sections",
      "Team section with dynamic layouts",
      "Awards and recognition display",
      "Client logo carousel",
      "New business inquiry form",
      "Animated page transitions",
    ],
    average_rating: 4.6,
    review_count: 15,
  },
  {
    id: "seed-5",
    name: "Finflow",
    slug: "finflow-dashboard",
    category: "Finance & Fintech",
    product_type: "app",
    price: 250000,
    currency: "NGN",
    overview: "A comprehensive fintech dashboard application with real-time analytics, transaction management, and investment portfolio tracking.",
    description: "Finflow is a production-ready fintech dashboard application designed for digital banking, investment platforms, and financial management tools. The interface combines data density with visual clarity, presenting complex financial information in an approachable and actionable format.\n\nThe dashboard includes interactive charts, transaction histories, budget tracking, portfolio summaries, and a full account management system. Built with security and compliance in mind.",
    demo_url: "https://finflow-demo.nuvia.store",
    is_featured: true,
    is_published: true,
    primary_image_url: "https://images.unsplash.com/photo-1551288049-bebda4e38f71?w=1200&h=900&fit=crop",
    images: [
      "https://images.unsplash.com/photo-1551288049-bebda4e38f71?w=1200&h=900&fit=crop",
      "https://images.unsplash.com/photo-1460925895917-afdab827c52f?w=1200&h=900&fit=crop",
    ],
    features: [
      "Real-time transaction monitoring",
      "Interactive portfolio charts",
      "Multi-account management",
      "Budget tracking and alerts",
      "Statement generation and export",
      "Two-factor authentication flow",
      "Responsive mobile layout",
      "Dark and light mode",
    ],
    average_rating: 4.9,
    review_count: 31,
  },
  {
    id: "seed-6",
    name: "Saveur",
    slug: "saveur-restaurant",
    category: "Food & Hospitality",
    product_type: "app",
    price: 175000,
    currency: "NGN",
    overview: "An elegant restaurant management application with online reservations, digital menus, order management, and kitchen display system.",
    description: "Saveur is a complete restaurant management application built for modern hospitality businesses. From online reservations to kitchen order displays, every workflow is designed to reduce friction and improve the dining experience on both sides of the kitchen door.\n\nThe customer-facing interface prioritises warmth and appetite appeal, while the management dashboard provides the real-time visibility operators need to run a smooth service.",
    demo_url: "https://saveur-demo.nuvia.store",
    is_featured: false,
    is_published: true,
    primary_image_url: "https://images.unsplash.com/photo-1517248135467-4c7edcad34c4?w=1200&h=900&fit=crop",
    images: [
      "https://images.unsplash.com/photo-1517248135467-4c7edcad34c4?w=1200&h=900&fit=crop",
    ],
    features: [
      "Online reservation system",
      "Digital menu with categories and allergens",
      "Table management floor plan",
      "Order management for staff",
      "Kitchen display system",
      "Loyalty and rewards module",
      "Revenue and occupancy analytics",
      "Customer feedback collection",
    ],
    average_rating: 4.7,
    review_count: 22,
  },
  {
    id: "seed-7",
    name: "Meridian",
    slug: "meridian-real-estate",
    category: "Architecture & Real Estate",
    product_type: "website",
    price: 195000,
    currency: "NGN",
    overview: "A premium real estate platform with property listings, virtual tours, mortgage calculator, and agent profiles.",
    description: "Meridian is a full-featured real estate platform built for agencies and developers who want to present properties with the sophistication they deserve. The search-first architecture makes finding the right property effortless, while the individual listing pages create an immersive showcase experience.\n\nThe platform supports residential, commercial, and off-plan properties with dedicated presentation formats for each. Agent profiles build trust, while the integrated mortgage calculator empowers buyers to make informed decisions.",
    demo_url: "https://meridian-demo.nuvia.store",
    is_featured: false,
    is_published: true,
    primary_image_url: "https://images.unsplash.com/photo-1560518883-ce09059eeffa?w=1200&h=900&fit=crop",
    images: [
      "https://images.unsplash.com/photo-1560518883-ce09059eeffa?w=1200&h=900&fit=crop",
      "https://images.unsplash.com/photo-1486325212027-8081e485255e?w=1200&h=900&fit=crop",
    ],
    features: [
      "Advanced property search with filters",
      "Individual property listing pages",
      "Virtual tour integration",
      "Mortgage repayment calculator",
      "Agent profiles and contact",
      "Saved properties and comparison",
      "Off-plan development showcase",
      "Neighbourhood information section",
    ],
    average_rating: 4.8,
    review_count: 17,
  },
  {
    id: "seed-8",
    name: "Canvas",
    slug: "canvas-portfolio",
    category: "Creative & Agency",
    product_type: "website",
    price: 65000,
    currency: "NGN",
    overview: "A minimal, editorial portfolio website for designers and creatives who want their work to speak for itself.",
    description: "Canvas is a minimal portfolio template that puts your work front and centre. The design philosophy is restraint — clean white space, elegant typography, and a grid system that makes even a modest body of work look curated and intentional.\n\nThe project pages support multiple media types, including full-bleed imagery, embedded videos, and detailed process documentation. Built for designers, photographers, illustrators, and any creative professional.",
    demo_url: "https://canvas-demo.nuvia.store",
    is_featured: false,
    is_published: true,
    primary_image_url: "https://images.unsplash.com/photo-1507238691740-187a5b1d37b8?w=1200&h=900&fit=crop",
    images: [
      "https://images.unsplash.com/photo-1507238691740-187a5b1d37b8?w=1200&h=900&fit=crop",
    ],
    features: [
      "Masonry and grid portfolio layouts",
      "Individual project case studies",
      "About and services page",
      "Blog section with editorial layout",
      "Contact form with validation",
      "Password-protected client portal",
      "Image lazy loading and optimisation",
      "Easy content management",
    ],
    average_rating: 4.5,
    review_count: 42,
  },
  {
    id: "seed-9",
    name: "Nexus AI",
    slug: "nexus-ai-startup",
    category: "SaaS & Technology",
    product_type: "website",
    price: 110000,
    currency: "NGN",
    overview: "A cutting-edge AI startup landing page with animated visualisations, product demos, and investor-ready messaging architecture.",
    description: "Nexus AI is a premium landing page template designed for artificial intelligence companies, machine learning startups, and deep tech businesses. The visual language communicates intelligence and precision through animated data visualisations, clean component design, and thoughtfully structured messaging.\n\nThe template includes sections for product capabilities, research highlights, team credentials, and a compelling investor pitch narrative. Every element is designed to establish credibility and drive signups.",
    demo_url: "https://nexus-demo.nuvia.store",
    is_featured: true,
    is_published: true,
    primary_image_url: "https://images.unsplash.com/photo-1677442135703-1787eea5ce01?w=1200&h=900&fit=crop",
    images: [
      "https://images.unsplash.com/photo-1677442135703-1787eea5ce01?w=1200&h=900&fit=crop",
      "https://images.unsplash.com/photo-1460925895917-afdab827c52f?w=1200&h=900&fit=crop",
    ],
    features: [
      "Animated AI visualisation hero",
      "Product capability showcase",
      "Research and publications section",
      "Team and advisors profiles",
      "Investor-focused messaging",
      "Waitlist and early access signup",
      "Press and media coverage section",
      "Technical specifications table",
    ],
    average_rating: 4.8,
    review_count: 28,
  },
];
